/** Static clinical catalogs: departments, tests, imaging, diagnoses, drugs, services. */

import type { Department } from "./types";

export const DEPARTMENTS: Omit<Department, "id">[] = [
  {
    slug: "emergency-casualty",
    name: "Emergency & Casualty",
    summary: "24/7 consultant-led emergency care with resuscitation and trauma bays.",
    description:
      "Our Emergency & Casualty unit runs around the clock with emergency physicians, trauma-trained nurses and immediate access to imaging, laboratory and theatre. Patients are triaged within five minutes of arrival using a four-colour priority system.",
    services: ["Triage", "Resuscitation", "Trauma care", "Emergency surgery referral", "Ambulance dispatch"],
    hours: "Open 24 hours, every day",
    phone: "+254 700 911 911",
    icon: "Siren",
    is_clinical: true,
  },
  {
    slug: "outpatient",
    name: "Outpatient Department",
    summary: "General and specialist consultations without admission.",
    description:
      "The Outpatient Department handles scheduled and walk-in consultations across general medicine and specialist clinics, supported by an electronic queue so patients know exactly where they stand.",
    services: ["General consultation", "Specialist clinics", "Review visits", "Minor procedures", "Health screening"],
    hours: "Mon–Sat, 7:00 AM – 8:00 PM",
    phone: "+254 700 820 100",
    icon: "Stethoscope",
    is_clinical: true,
  },
  {
    slug: "inpatient-wards",
    name: "Inpatient / Wards",
    summary: "General, private and high-dependency wards with 24-hour nursing.",
    description:
      "Abancool operates 180 inpatient beds across general, amenity and private wards. Every bed is tracked in real time, and nursing rounds, medication administration and doctor reviews are recorded electronically.",
    services: ["General ward", "Private rooms", "High dependency", "Isolation", "Nursing care"],
    hours: "Visiting: 11:00 AM – 1:00 PM and 5:00 PM – 7:00 PM",
    phone: "+254 700 820 110",
    icon: "BedDouble",
    is_clinical: true,
  },
  {
    slug: "icu",
    name: "Intensive Care Unit",
    summary: "Twelve-bed ICU with ventilator support and 1:1 critical care nursing.",
    description:
      "The ICU is staffed by intensivists and critical care nurses with invasive monitoring, ventilators, dialysis support and continuous cardiac telemetry.",
    services: ["Ventilator support", "Invasive monitoring", "Post-operative critical care", "Sepsis management"],
    hours: "Open 24 hours, every day",
    phone: "+254 700 820 115",
    icon: "Activity",
    is_clinical: true,
  },
  {
    slug: "theatre-surgery",
    name: "Theatre / Surgery",
    summary: "Four modular theatres for elective and emergency surgery.",
    description:
      "Our theatre complex runs elective lists six days a week plus a 24-hour emergency theatre, with laminar-flow ventilation, modern anaesthesia machines and a dedicated recovery bay.",
    services: ["Elective surgery", "Emergency surgery", "Day surgery", "Laparoscopy", "Anaesthesia services"],
    hours: "Elective: Mon–Sat 8:00 AM – 6:00 PM · Emergency: 24 hours",
    phone: "+254 700 820 120",
    icon: "Scissors",
    is_clinical: true,
  },
  {
    slug: "maternity",
    name: "Maternity",
    summary: "Antenatal, delivery, postnatal and newborn care.",
    description:
      "Mothers deliver in private labour rooms attended by obstetricians and midwives, with an adjoining newborn unit and 24-hour emergency caesarean capability.",
    services: ["Antenatal clinic", "Labour & delivery", "Caesarean section", "Postnatal care", "Newborn unit"],
    hours: "Open 24 hours, every day",
    phone: "+254 700 820 125",
    icon: "Baby",
    is_clinical: true,
  },
  {
    slug: "pediatrics",
    name: "Pediatrics",
    summary: "Child-friendly clinics, immunisation and growth monitoring.",
    description:
      "Paediatricians care for newborns through adolescents, with growth charts, immunisation schedules and weight-based medication dosing built into every consultation.",
    services: ["Child wellness clinic", "Immunisation", "Growth monitoring", "Paediatric admissions", "Nutrition advice"],
    hours: "Mon–Sat, 8:00 AM – 6:00 PM",
    phone: "+254 700 820 130",
    icon: "ToyBrick",
    is_clinical: true,
  },
  {
    slug: "obstetrics-gynecology",
    name: "Obstetrics & Gynecology",
    summary: "Women's health from fertility to menopause.",
    description:
      "Comprehensive women's health services including fertility assessment, gynaecological surgery, cervical screening and high-risk pregnancy management.",
    services: ["Gynae clinic", "Fertility assessment", "Cervical screening", "Gynae surgery", "Family planning"],
    hours: "Mon–Fri, 8:00 AM – 5:00 PM",
    phone: "+254 700 820 131",
    icon: "HeartPulse",
    is_clinical: true,
  },
  {
    slug: "general-medicine",
    name: "General Medicine",
    summary: "Diagnosis and management of adult medical conditions.",
    description:
      "Physicians manage diabetes, hypertension, respiratory disease, infections and complex multi-system illness, with structured chronic-care follow-up.",
    services: ["Adult consultation", "Chronic disease clinic", "Diabetes care", "Hypertension clinic", "Infectious disease"],
    hours: "Mon–Sat, 8:00 AM – 6:00 PM",
    phone: "+254 700 820 140",
    icon: "Stethoscope",
    is_clinical: true,
  },
  {
    slug: "general-surgery",
    name: "General Surgery",
    summary: "Open and laparoscopic surgical care for adults and children.",
    description:
      "Our surgeons handle hernia repair, gallbladder disease, appendicitis, thyroid surgery and soft tissue procedures, including minimally invasive approaches.",
    services: ["Surgical consultation", "Hernia repair", "Laparoscopic surgery", "Wound care", "Day-case surgery"],
    hours: "Mon–Sat, 8:00 AM – 5:00 PM",
    phone: "+254 700 820 141",
    icon: "Scissors",
    is_clinical: true,
  },
  {
    slug: "orthopedics",
    name: "Orthopedics",
    summary: "Bone, joint and sports injury care with on-site imaging.",
    description:
      "Orthopaedic surgeons manage fractures, joint replacement, spine conditions and sports injuries, supported by digital X-ray and physiotherapy.",
    services: ["Fracture clinic", "Joint replacement", "Sports injury", "Spine clinic", "Casting & traction"],
    hours: "Mon–Sat, 8:00 AM – 5:00 PM",
    phone: "+254 700 820 142",
    icon: "Bone",
    is_clinical: true,
  },
  {
    slug: "dental",
    name: "Dental",
    summary: "Preventive, restorative and surgical dentistry.",
    description:
      "The dental suite offers scaling, fillings, root canal therapy, extractions, orthodontic referral and cosmetic dentistry with digital dental imaging.",
    services: ["Dental check-up", "Scaling & polishing", "Fillings", "Root canal", "Extraction", "Dental imaging"],
    hours: "Mon–Sat, 8:00 AM – 6:00 PM",
    phone: "+254 700 820 150",
    icon: "Smile",
    is_clinical: true,
  },
  {
    slug: "ent",
    name: "ENT",
    summary: "Ear, nose and throat diagnosis and surgery.",
    description:
      "ENT surgeons manage hearing loss, sinus disease, tonsillitis, voice disorders and head and neck conditions with endoscopic assessment.",
    services: ["ENT consultation", "Audiometry", "Endoscopy", "Tonsillectomy", "Sinus surgery"],
    hours: "Mon–Fri, 9:00 AM – 5:00 PM",
    phone: "+254 700 820 151",
    icon: "Ear",
    is_clinical: true,
  },
  {
    slug: "ophthalmology",
    name: "Ophthalmology",
    summary: "Eye examinations, cataract surgery and optical services.",
    description:
      "Comprehensive eye care including refraction, glaucoma screening, diabetic retinopathy assessment and day-case cataract surgery.",
    services: ["Eye examination", "Refraction", "Glaucoma screening", "Cataract surgery", "Optical dispensing"],
    hours: "Mon–Sat, 8:30 AM – 5:00 PM",
    phone: "+254 700 820 152",
    icon: "Eye",
    is_clinical: true,
  },
  {
    slug: "cardiology",
    name: "Cardiology",
    summary: "Heart diagnostics, ECG, echocardiography and cardiac clinics.",
    description:
      "Cardiologists assess chest pain, heart failure, arrhythmia and hypertension with ECG, echocardiography, treadmill testing and Holter monitoring.",
    services: ["Cardiology consultation", "ECG", "Echocardiogram", "Treadmill test", "Holter monitoring"],
    hours: "Mon–Fri, 8:00 AM – 5:00 PM",
    phone: "+254 700 820 160",
    icon: "HeartPulse",
    is_clinical: true,
  },
  {
    slug: "neurology",
    name: "Neurology",
    summary: "Brain, spine and nerve disorder management.",
    description:
      "Neurologists diagnose and treat stroke, epilepsy, headache disorders, neuropathy and movement disorders, with CT and MRI available on site.",
    services: ["Neurology consultation", "EEG", "Stroke follow-up", "Epilepsy clinic", "Headache clinic"],
    hours: "Mon–Fri, 9:00 AM – 4:00 PM",
    phone: "+254 700 820 161",
    icon: "Brain",
    is_clinical: true,
  },
  {
    slug: "dermatology",
    name: "Dermatology",
    summary: "Skin, hair and nail conditions for all ages.",
    description:
      "Dermatologists treat acne, eczema, psoriasis, fungal infections and skin lesions, with minor dermatological surgery and cosmetic procedures.",
    services: ["Skin consultation", "Acne treatment", "Eczema management", "Minor skin surgery", "Dermoscopy"],
    hours: "Mon, Wed, Fri, 9:00 AM – 4:00 PM",
    phone: "+254 700 820 162",
    icon: "Sparkles",
    is_clinical: true,
  },
  {
    slug: "psychiatry",
    name: "Psychiatry / Mental Health",
    summary: "Confidential mental health assessment, therapy and follow-up.",
    description:
      "Our mental health team offers psychiatric assessment, counselling, therapy and medication management in a private, stigma-free setting.",
    services: ["Psychiatric assessment", "Counselling", "Therapy sessions", "Medication review", "Addiction support"],
    hours: "Mon–Fri, 9:00 AM – 5:00 PM",
    phone: "+254 700 820 163",
    icon: "Brain",
    is_clinical: true,
  },
  {
    slug: "radiology",
    name: "Radiology",
    summary: "Digital X-ray, ultrasound, CT and MRI with same-day reporting.",
    description:
      "The imaging department operates digital radiography, 4D ultrasound, 64-slice CT and 1.5T MRI, with radiologist reports typically issued the same day.",
    services: ["X-Ray", "Ultrasound", "CT scan", "MRI", "Mammography", "Dental OPG"],
    hours: "Mon–Sat 7:00 AM – 9:00 PM · Emergency imaging 24 hours",
    phone: "+254 700 820 170",
    icon: "ScanLine",
    is_clinical: true,
  },
  {
    slug: "laboratory",
    name: "Laboratory",
    summary: "ISO-aligned diagnostic laboratory with rapid turnaround.",
    description:
      "Our laboratory covers haematology, clinical chemistry, microbiology, serology and histology, with urgent results released within one hour.",
    services: ["Haematology", "Clinical chemistry", "Microbiology", "Serology", "Sample collection"],
    hours: "Open 24 hours, every day",
    phone: "+254 700 820 171",
    icon: "FlaskConical",
    is_clinical: true,
  },
  {
    slug: "pharmacy",
    name: "Pharmacy",
    summary: "In-house pharmacy with genuine, quality-assured medicines.",
    description:
      "Registered pharmacists review every prescription for dosage, interactions and allergies before dispensing, and counsel patients on how to take their medicines.",
    services: ["Prescription dispensing", "Medication counselling", "Chronic refills", "Over-the-counter", "Medicine delivery"],
    hours: "Open 24 hours, every day",
    phone: "+254 700 820 172",
    icon: "Pill",
    is_clinical: true,
  },
  {
    slug: "physiotherapy",
    name: "Physiotherapy",
    summary: "Rehabilitation after injury, surgery or stroke.",
    description:
      "Physiotherapists deliver individualised rehabilitation programmes for musculoskeletal pain, post-operative recovery, stroke and respiratory conditions.",
    services: ["Musculoskeletal therapy", "Post-op rehabilitation", "Stroke rehabilitation", "Chest physiotherapy", "Home exercise plans"],
    hours: "Mon–Sat, 8:00 AM – 6:00 PM",
    phone: "+254 700 820 180",
    icon: "Dumbbell",
    is_clinical: true,
  },
  {
    slug: "nutrition-dietetics",
    name: "Nutrition & Dietetics",
    summary: "Clinical nutrition support and therapeutic diets.",
    description:
      "Dietitians create therapeutic meal plans for diabetes, kidney disease, hypertension, weight management, paediatric malnutrition and inpatient nutrition.",
    services: ["Diet assessment", "Diabetic diet planning", "Weight management", "Paediatric nutrition", "Inpatient nutrition"],
    hours: "Mon–Fri, 8:00 AM – 5:00 PM",
    phone: "+254 700 820 181",
    icon: "Salad",
    is_clinical: true,
  },
  {
    slug: "renal-dialysis",
    name: "Renal / Dialysis",
    summary: "Ten-station dialysis unit with nephrology clinics.",
    description:
      "The renal unit provides haemodialysis three shifts a day, chronic kidney disease monitoring, vascular access care and transplant referral.",
    services: ["Haemodialysis", "Nephrology clinic", "CKD monitoring", "Vascular access care"],
    hours: "Mon–Sat, 6:00 AM – 10:00 PM",
    phone: "+254 700 820 190",
    icon: "Droplets",
    is_clinical: true,
  },
  {
    slug: "oncology",
    name: "Oncology",
    summary: "Cancer diagnosis, chemotherapy and supportive care.",
    description:
      "Oncologists coordinate diagnosis, staging, chemotherapy day care, pain management and palliative support in a calm, dedicated unit.",
    services: ["Oncology consultation", "Chemotherapy day care", "Cancer screening", "Palliative care", "Tumour board review"],
    hours: "Mon–Fri, 8:00 AM – 5:00 PM",
    phone: "+254 700 820 191",
    icon: "Ribbon",
    is_clinical: true,
  },
  {
    slug: "ambulance",
    name: "Ambulance Services",
    summary: "Advanced life support ambulances dispatched across the county.",
    description:
      "Our fleet of advanced and basic life support ambulances is staffed by paramedics and connected directly to the emergency department for pre-arrival alerts.",
    services: ["Emergency response", "Inter-facility transfer", "Advanced life support", "Event standby"],
    hours: "Open 24 hours, every day",
    phone: "+254 700 911 911",
    icon: "Ambulance",
    is_clinical: false,
  },
];

export const LAB_TESTS = [
  { code: "CBC", name: "Complete Blood Count", price: 1200, sample: "Blood" },
  { code: "UEC", name: "Urea, Electrolytes & Creatinine", price: 2500, sample: "Blood" },
  { code: "LFT", name: "Liver Function Test", price: 2800, sample: "Blood" },
  { code: "HBA1C", name: "HbA1c", price: 2200, sample: "Blood" },
  { code: "MPS", name: "Malaria Parasite Smear", price: 600, sample: "Blood" },
  { code: "URIN", name: "Urinalysis", price: 700, sample: "Urine" },
  { code: "PREG", name: "Pregnancy Test (BHCG)", price: 500, sample: "Urine" },
  { code: "LIPID", name: "Lipid Profile", price: 2400, sample: "Blood" },
  { code: "BGRP", name: "Blood Group & Rhesus", price: 500, sample: "Blood" },
  { code: "CREA", name: "Serum Creatinine", price: 900, sample: "Blood" },
  { code: "CRP", name: "C-Reactive Protein", price: 1500, sample: "Blood" },
  { code: "TFT", name: "Thyroid Function Test", price: 3500, sample: "Blood" },
  { code: "STOOL", name: "Stool Microscopy", price: 600, sample: "Stool" },
  { code: "HIV", name: "HIV Screening", price: 800, sample: "Blood" },
  { code: "ESR", name: "Erythrocyte Sedimentation Rate", price: 700, sample: "Blood" },
];

export const LAB_PANELS: Record<string, { parameter: string; unit: string; reference: string; normal: string }[]> = {
  CBC: [
    { parameter: "WBC", unit: "10^9/L", reference: "4.0 – 11.0", normal: "7.4" },
    { parameter: "RBC", unit: "10^12/L", reference: "4.5 – 5.9", normal: "5.1" },
    { parameter: "Haemoglobin", unit: "g/dL", reference: "12.0 – 16.0", normal: "13.4" },
    { parameter: "Haematocrit", unit: "%", reference: "36 – 48", normal: "41" },
    { parameter: "Platelets", unit: "10^9/L", reference: "150 – 450", normal: "265" },
  ],
  UEC: [
    { parameter: "Sodium", unit: "mmol/L", reference: "135 – 145", normal: "139" },
    { parameter: "Potassium", unit: "mmol/L", reference: "3.5 – 5.1", normal: "4.2" },
    { parameter: "Urea", unit: "mmol/L", reference: "2.5 – 7.1", normal: "4.8" },
    { parameter: "Creatinine", unit: "umol/L", reference: "62 – 106", normal: "88" },
  ],
  LFT: [
    { parameter: "ALT", unit: "U/L", reference: "7 – 56", normal: "28" },
    { parameter: "AST", unit: "U/L", reference: "10 – 40", normal: "24" },
    { parameter: "Total Bilirubin", unit: "umol/L", reference: "3 – 17", normal: "11" },
    { parameter: "Albumin", unit: "g/L", reference: "35 – 50", normal: "42" },
  ],
  HBA1C: [{ parameter: "HbA1c", unit: "%", reference: "4.0 – 5.6", normal: "5.4" }],
  MPS: [{ parameter: "Malaria Parasites", unit: "", reference: "Not seen", normal: "Not seen" }],
  URIN: [
    { parameter: "Colour", unit: "", reference: "Yellow", normal: "Yellow" },
    { parameter: "Protein", unit: "", reference: "Negative", normal: "Negative" },
    { parameter: "Glucose", unit: "", reference: "Negative", normal: "Negative" },
    { parameter: "Pus Cells", unit: "/hpf", reference: "0 – 5", normal: "2" },
  ],
  PREG: [{ parameter: "Beta HCG", unit: "", reference: "Negative", normal: "Negative" }],
  LIPID: [
    { parameter: "Total Cholesterol", unit: "mmol/L", reference: "< 5.2", normal: "4.6" },
    { parameter: "HDL", unit: "mmol/L", reference: "> 1.0", normal: "1.4" },
    { parameter: "LDL", unit: "mmol/L", reference: "< 3.4", normal: "2.9" },
    { parameter: "Triglycerides", unit: "mmol/L", reference: "< 1.7", normal: "1.2" },
  ],
  BGRP: [{ parameter: "Blood Group", unit: "", reference: "—", normal: "O Positive" }],
  CREA: [{ parameter: "Creatinine", unit: "umol/L", reference: "62 – 106", normal: "85" }],
  CRP: [{ parameter: "CRP", unit: "mg/L", reference: "< 5", normal: "3" }],
  TFT: [
    { parameter: "TSH", unit: "mIU/L", reference: "0.4 – 4.0", normal: "2.1" },
    { parameter: "Free T4", unit: "pmol/L", reference: "9 – 19", normal: "14" },
  ],
  STOOL: [{ parameter: "Ova & Cysts", unit: "", reference: "Not seen", normal: "Not seen" }],
  HIV: [{ parameter: "HIV 1 & 2 Antibodies", unit: "", reference: "Non-reactive", normal: "Non-reactive" }],
  ESR: [{ parameter: "ESR", unit: "mm/hr", reference: "0 – 20", normal: "12" }],
};

export const RADIOLOGY_STUDIES = [
  { modality: "X-Ray", study: "Chest X-Ray (PA)", price: 2500 },
  { modality: "X-Ray", study: "Knee X-Ray (AP/Lateral)", price: 2800 },
  { modality: "X-Ray", study: "Lumbar Spine X-Ray", price: 3200 },
  { modality: "Ultrasound", study: "Abdominal Ultrasound", price: 3500 },
  { modality: "Ultrasound", study: "Obstetric Ultrasound", price: 3000 },
  { modality: "Ultrasound", study: "Pelvic Ultrasound", price: 3000 },
  { modality: "CT", study: "CT Brain (Non-contrast)", price: 12000 },
  { modality: "CT", study: "CT Abdomen & Pelvis", price: 18000 },
  { modality: "MRI", study: "MRI Lumbar Spine", price: 25000 },
  { modality: "MRI", study: "MRI Brain", price: 28000 },
  { modality: "Mammography", study: "Bilateral Mammogram", price: 8500 },
  { modality: "OPG", study: "Dental OPG", price: 4000 },
] as const;

export const DIAGNOSES = [
  { code: "J06.9", label: "Acute upper respiratory infection, unspecified" },
  { code: "B54", label: "Unspecified malaria" },
  { code: "A09", label: "Infectious gastroenteritis and colitis" },
  { code: "I10", label: "Essential (primary) hypertension" },
  { code: "E11.9", label: "Type 2 diabetes mellitus without complications" },
  { code: "J45.9", label: "Asthma, unspecified" },
  { code: "K29.7", label: "Gastritis, unspecified" },
  { code: "N39.0", label: "Urinary tract infection, site not specified" },
  { code: "M54.5", label: "Low back pain" },
  { code: "R51", label: "Headache" },
  { code: "L23.9", label: "Allergic contact dermatitis, unspecified cause" },
  { code: "H66.9", label: "Otitis media, unspecified" },
  { code: "D50.9", label: "Iron deficiency anaemia, unspecified" },
  { code: "J18.9", label: "Pneumonia, unspecified organism" },
  { code: "K02.9", label: "Dental caries, unspecified" },
  { code: "O80", label: "Single spontaneous delivery" },
  { code: "S52.5", label: "Fracture of lower end of radius" },
  { code: "I50.9", label: "Heart failure, unspecified" },
  { code: "F32.9", label: "Depressive episode, unspecified" },
  { code: "N18.3", label: "Chronic kidney disease, stage 3" },
];

export const DRUGS = [
  { name: "Amoxil 500mg", generic: "Amoxicillin", strength: "500 mg", price: 25, form: "Capsule" },
  { name: "Panadol 500mg", generic: "Paracetamol", strength: "500 mg", price: 8, form: "Tablet" },
  { name: "Brufen 400mg", generic: "Ibuprofen", strength: "400 mg", price: 12, form: "Tablet" },
  { name: "Coartem 20/120", generic: "Artemether/Lumefantrine", strength: "20/120 mg", price: 45, form: "Tablet" },
  { name: "Flagyl 400mg", generic: "Metronidazole", strength: "400 mg", price: 15, form: "Tablet" },
  { name: "Zithromax 500mg", generic: "Azithromycin", strength: "500 mg", price: 120, form: "Tablet" },
  { name: "Glucophage 500mg", generic: "Metformin", strength: "500 mg", price: 14, form: "Tablet" },
  { name: "Amlodipine 5mg", generic: "Amlodipine", strength: "5 mg", price: 10, form: "Tablet" },
  { name: "Losartan 50mg", generic: "Losartan Potassium", strength: "50 mg", price: 18, form: "Tablet" },
  { name: "Ventolin Inhaler", generic: "Salbutamol", strength: "100 mcg", price: 850, form: "Inhaler" },
  { name: "Omeprazole 20mg", generic: "Omeprazole", strength: "20 mg", price: 16, form: "Capsule" },
  { name: "Cetirizine 10mg", generic: "Cetirizine", strength: "10 mg", price: 9, form: "Tablet" },
  { name: "Ceftriaxone 1g", generic: "Ceftriaxone", strength: "1 g", price: 320, form: "Injection" },
  { name: "Normal Saline 500ml", generic: "Sodium Chloride 0.9%", strength: "500 ml", price: 180, form: "IV Fluid" },
  { name: "Ferrous Sulphate", generic: "Ferrous Sulphate", strength: "200 mg", price: 7, form: "Tablet" },
  { name: "Diclofenac 50mg", generic: "Diclofenac Sodium", strength: "50 mg", price: 11, form: "Tablet" },
  { name: "Hydrocortisone Cream", generic: "Hydrocortisone", strength: "1%", price: 260, form: "Cream" },
  { name: "ORS Sachet", generic: "Oral Rehydration Salts", strength: "20.5 g", price: 35, form: "Sachet" },
];

export const SERVICE_CATALOG = [
  { name: "General Consultation", department: "outpatient", price: 1000 },
  { name: "Specialist Consultation", department: "outpatient", price: 3000 },
  { name: "Emergency Assessment", department: "emergency-casualty", price: 2500 },
  { name: "Dental Check-up", department: "dental", price: 1500 },
  { name: "Antenatal Visit", department: "maternity", price: 1800 },
  { name: "Child Wellness Visit", department: "pediatrics", price: 1500 },
  { name: "Physiotherapy Session", department: "physiotherapy", price: 2000 },
  { name: "Dialysis Session", department: "renal-dialysis", price: 9500 },
  { name: "Eye Examination", department: "ophthalmology", price: 1800 },
  { name: "Echocardiogram", department: "cardiology", price: 6500 },
];

export const HEALTH_PACKAGES = [
  {
    name: "Essential Health Check",
    price: 6500,
    for: "Adults 18+ · Annual screening",
    includes: ["Doctor consultation", "Complete blood count", "Urinalysis", "Blood sugar", "Blood pressure review", "BMI assessment"],
  },
  {
    name: "Executive Wellness",
    price: 24500,
    for: "Professionals 35+ · Comprehensive",
    includes: ["Physician review", "Full blood workup", "Lipid profile", "Liver & kidney function", "ECG", "Chest X-Ray", "Abdominal ultrasound", "Dietitian session"],
  },
  {
    name: "Women's Health Package",
    price: 15500,
    for: "Women 25+",
    includes: ["Gynaecologist consultation", "Pap smear", "Breast examination", "Pelvic ultrasound", "Haemoglobin", "Thyroid function"],
  },
  {
    name: "Diabetes & Heart Care",
    price: 12800,
    for: "Chronic condition follow-up",
    includes: ["Physician review", "HbA1c", "Lipid profile", "Kidney function", "ECG", "Eye screening", "Nutrition counselling"],
  },
  {
    name: "Maternity Package",
    price: 95000,
    for: "Normal delivery, 2-night stay",
    includes: ["Antenatal visits", "Delivery by obstetrician", "Midwife care", "Newborn assessment", "Private room", "Postnatal review"],
  },
  {
    name: "Child Wellness Package",
    price: 5500,
    for: "Children 0–12 years",
    includes: ["Paediatric consultation", "Growth assessment", "Immunisation review", "Haemoglobin", "Deworming", "Nutrition advice"],
  },
];

export const TRIAGE_COLORS = {
  RED: "Immediate — life threatening",
  ORANGE: "Very urgent — within 10 minutes",
  YELLOW: "Urgent — within 60 minutes",
  GREEN: "Standard — within 2 hours",
} as const;
